apiVersion: argoproj.io/v1beta1
kind: ArgoCD
metadata:
  name: openshift-gitops
spec:
  rbac:
    defaultPolicy: read-only
    policy: |-
      g, system:cluster-admins, role:admin
      g, cluster-admins, role:admin
      g, my-custom-group, role:admin