apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
  - target:
      kind: ArgoCD
      name: openshift-gitops
      namespace: openshift-gitops
    patch: |-
      apiVersion: argoproj.io/v1beta1
      kind: ArgoCD
      metadata:
        name: openshift-gitops
      spec:
        extraConfig:
          accounts.admin: apiKey