apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openshift-gitops
resources:
- ../../base

patches:
- target:
    kind: ArgoCD
    name: openshift-gitops
    namespace: openshift-gitops
  patch: |-
    apiVersion: argoproj.io/v1beta1
    kind: ArgoCD
    metadata:
      name: openshift-gitops
    spec:
      rbac:
        defaultPolicy: read-only
        policy: |-
          g, system:cluster-admins, role:admin
          g, cluster-admins, role:admin
          g, my-custom-group, role:admin